#!/usr/bin/env bash

# Sample usage: start execute|compile [-ix] <source file path>
if [ ! -d "classes" ]; then
	mkdir classes
fi

rm -rf classes/*

javac -classpath classes -d classes -sourcepath src src/*.java

java -classpath classes C compile -xi "$@"

